version: "3"
services:   
  zookeeper:
    build:
      context: .
    command: ['./bin/zookeeper-server-start.sh', '/config/zookeeper']
    volumes:
      - ./config:/config
  broker1:
    build:
      context: .
    command: ['./bin/kafka-server-start.sh', '/config/localhost/broker1']
    ports:
      - 9093:9093
    volumes:
      - ./config:/config
  broker2:
    build:
      context: .
    command: ['./bin/kafka-server-start.sh', '/config/localhost/broker2']
    ports: 
      - 9094:9094
    volumes:
      - ./config:/config

  broker3:
    build:
      context: .
    command: ['./bin/kafka-server-start.sh', '/config/localhost/broker3']
    ports:
      - 9095:9095
    volumes:
      - ./config:/config