version: "3"
services:   
  zookeeper:
    build:
      context: .
    command: ['./bin/zookeeper-server-start.sh', '/config/zookeeper']
    volumes:
      - ./config:/config
      - ./state/zookeeper:/zookerper

  broker1:
    build:
      context: .
    command: ['./bin/kafka-server-start.sh', '/config/broker1']
    volumes:
      - ./config:/config
      - ./state/broker1:/kafka-logs

  broker2:
    build:
      context: .
    command: ['./bin/kafka-server-start.sh', '/config/broker2']
    volumes:
      - ./config:/config
      - ./state/broker2:/kafka-logs


  broker3:
    build:
      context: .
    command: ['./bin/kafka-server-start.sh', '/config/broker3']
    volumes:
      - ./config:/config
      - ./state/broker3:/kafka-logs
