version: "3"
services:   
  zookeeper:
    build:
      context: .
    command: ['./bin/zookeeper-server-start.sh', '/config/zookeeper']
    volumes:
      - ./config:/config
  broker1:
    build:
      context: .
    command: ['./bin/kafka-server-start.sh', '/config/localhost/broker1']
    ports:
      - 29092:29092
    volumes:
      - ./config:/config
  broker2:
    build:
      context: .
    command: ['./bin/kafka-server-start.sh', '/config/localhost/broker2']
    ports: 
      - 29093:29093
    volumes:
      - ./config:/config

  broker3:
    build:
      context: .
    command: ['./bin/kafka-server-start.sh', '/config/localhost/broker3']
    ports:
      - 29094:29094
    volumes:
      - ./config:/config


  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'localhost:29092, localhost:29093, localhost:29094'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081