version: "3"
services:   
  zookeeper:
    build:
      context: .
    command: ['./bin/zookeeper-server-start.sh', '/config/zookeeper']
    volumes:
      - ./config:/config
      - ./state/zookeeper:/zookerper

  broker1:
    build:
      context: .
    command: ['./bin/kafka-server-start.sh', '/config/broker1']
    volumes:
      - ./config:/config
      - ./state/broker1:/kafka-logs

  broker2:
    build:
      context: .
    command: ['./bin/kafka-server-start.sh', '/config/broker2']
    volumes:
      - ./config:/config
      - ./state/broker2:/kafka-logs


  broker3:
    build:
      context: .
    command: ['./bin/kafka-server-start.sh', '/config/broker3']
    volumes:
      - ./config:/config
      - ./state/broker3:/kafka-logs

  microservicioA:
    image: node
    deploy:
      replicas: 5
    command: ['npm', 'start']
    depends_on:
      - broker1
      - broker2
      - broker3
    working_dir: /app
    volumes:
      - ./src/microservicioA:/app


  microservicioB:
    image: node
    deploy:
      replicas: 1
    command: ['npm', 'run', 'start-example']
    depends_on:
      - broker1
      - broker2
      - broker3
    working_dir: /app
    volumes:
      - ./src/microservicioA:/app