version: "3"
services:   
  zookeeper:
    build:
      context: .
    command: ['./bin/zookeeper-server-start.sh', '/config/zookeeper']
    volumes:
      - ./config:/config

  broker1:
    build:
      context: .
    command: ['./bin/kafka-server-start.sh', '/config/broker1']
    volumes:
      - ./config:/config

  broker2:
    build:
      context: .
    command: ['./bin/kafka-server-start.sh', '/config/broker2']
    volumes:
      - ./config:/config

  broker3:
    build:
      context: .
    command: ['./bin/kafka-server-start.sh', '/config/broker3']
    volumes:
      - ./config:/config